language: node_js
node_js:
- 8
install:
- npm install -g bower
- npm install
before_script: npm run lint
script: npm run build
before_deploy:
- tar -zcf ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz www
deploy:
  provider: releases
  api_key:
    secure: "Lsk6HLhVAi//+KrjYPUYTRzm+t0urSFgACRwpk+vkAGyMo/RSvLzRTWrUPa40Mv4VvatlidbviyLgpBfu4dX0mg+80NzrVF3OE+lctWw6pB8Ajr2fyY1K6YYWM3JHsTPmfmf/T6Ii6lrMT+a1Mbfv+f++VxhhIzYdHpZRjrh9nJnBToCJGCDl9oCNxNMGM3+/MVivTlnKkgHR9XITm35pyHs3Cgxsn14XHPIAwKnR6mBE+xX9mv1Y3KbiqJeeRE8e0kha3eXKSLZe+B1Hfl41aPvPKvmjDyF+4jGsaTE/plN8sJXRQLKM0KU827fX7IgGK+xzxrtnTMHyc6XxBNdMVJH/BlAzdWgzqjk/vACS1vDUXSGuSFAp2O507yXlWeFRPTQB9/fxim+qnuhH8IuFls8cCydqRK4pF5SjfJrzCDKQoQrvRt7/ey3sg14gvNtRMcB8jGFWkArYjxjQB7hmT9oYfMhwge0DHKxiG1hu3s8hzzsz1eh0S4LmLMGliNehLVXN4eA8aw6Wjc7RewrCqFOipclje8zKA6IQoYAZPXptQPpXkTXeDWYOGY/IPN+bfncPxAVScXYE6XpWAoDWxlbmyHSERcdlESVbVqtbSf4e9D8dZbKWr/VLggpV9wSju8fcPT28BYwj8wFi1UxvNrNMM7cqjWDcZN5PL5Q2Vw="
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.tar.gz
  on:
    repo: izissise/nginx-explorer
    tags: true
